services:
  nginx:
    restart: unless-stopped
    stop_signal: SIGKILL
    depends_on: []
    networks: [net-food]
    ports:
      - "127.0.0.1:9090:9090"
    volumes:
      - ./build/nginx/food.conf:/etc/nginx/conf.d/default.conf:ro
    build:
      dockerfile: ./build/dockerfiles/nginx.Dockerfile

  webserver:
    build:
      dockerfile: ./build/dockerfiles/webserver.Dockerfile
    restart: unless-stopped
    depends_on:
      - postgres
      - jaeger
    networks:
      - net-food
    env_file: [.env]

  postgres:
    shm_size: 128mb
    restart: unless-stopped
    networks:
      - net-food
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres-vol:/var/lib/postgresql/data
    build:
      dockerfile: ./build/dockerfiles/postgres.Dockerfile

networks:
  net-food:
    driver: bridge

volumes:
  postgres-vol:
  jaeger-vol:
