services:
  nginx-dev:
    restart: unless-stopped
    stop_signal: SIGKILL
    depends_on: [ ]
    networks: [ net-food-dev ]
    ports:
      - "127.0.0.1:8443:443"
    volumes:
      - ./data/nginx/recipe-dev.conf:/etc/nginx/conf.d/default.conf:ro
      - ./data/nginx/recipe-dev.crt:/certs/nginx.crt:ro
      - ./data/nginx/recipe-dev.key:/certs/nginx.key:ro
    build:
      dockerfile: ./build/dockerfiles/nginx-dev.Dockerfile

  webserver-dev:
    build:
      dockerfile: ./build/dockerfiles/webserver-dev.Dockerfile
    restart: unless-stopped
    depends_on:
      - postgres-dev
    networks:
      - net-food-dev
    volumes:
      - ./webserver/migrations:/migrations
    env_file: [ .env ]

  postgres-dev:
    shm_size: 128mb
    restart: unless-stopped
    networks:
      - net-food-dev
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres-dev:/var/lib/postgresql/data
    build:
      dockerfile: ./build/dockerfiles/postgres.Dockerfile

  frontend-dev:
    restart: unless-stopped
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
    env_file: [ .env ]
    networks: [ net-food-dev ]
    user: "${UID}:${GID}"
    build:
      dockerfile: ./build/dockerfiles/frontend-dev.Dockerfile

networks:
  net-food-dev:
    driver: bridge

volumes:
  postgres-dev:
    name: postgres-dev-vol
