[package]
name = "webserver"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
thiserror = "~2"
rand = "0.9.1"
dotenv = "0.15.0"

# Webframework
axum = { version = "~0.8", features = ["ws"] } # Main web library
galvyn = { version = "~0.1", git = "https://github.com/myOmikron/galvyn" }
tower = { version = "~0.5", features = ["full"] } # Base traits
tower-http = { version = "~0.6", features = ["trace"] } # Common middlewares
tower-sessions = { version = "~0.14" }
schemars = { version = "~0.8", features = [
    "uuid1",
    "raw_value",
] }
reqwest = "0.12.23"

# Cli
clap = { version = "~4", features = ["derive"] }

# Logging
tracing = { version = "~0.1" } # Base API
tracing-subscriber = { version = "~0.3", features = [
    "tracing-log",
    "env-filter",
] }
tracing-opentelemetry = { version = "0.25" }
opentelemetry = { version = "0.24" }
opentelemetry_sdk = { version = "0.24", features = ["rt-tokio"] }
opentelemetry-otlp = { version = "0.17" }

# Datatypes
uuid = { version = "~1", features = ["serde", "v4"] }
time = { version = "~0.3" }

# Database
rorm = { version = "~0.7", default-features = false, features = ["postgres-only", "cli", "time", "uuid", "schemars"] }

# Async
tokio = { version = "~1", features = ["full"] }
futures-lite = { version = "~2" }
futures-util = "0.3.31"

# Json
serde = { version = "~1", features = ["derive"] }
serde_repr = { version = "~0.1" }
serde_plain = "1.0.0"
serde_json = "1.0.140"

# GRPC
tonic = { version = "~0.12", default-features = false, features = [
    "channel",
    "codegen",
    "prost",
    "tls",
    "tls-native-roots",
] }

jsonwebtoken = "9.3.1"
argon2 = { version = "0.5.3", features = ["std"] }
rpassword = "7.3.1"

# Authentication
openidconnect = { version = "~4", features = ["accept-rfc3339-timestamps", "timing-resistant-secret-traits"] }
url = "2.5.4"

[build-dependencies]