/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppAppTagsIndexRouteImport } from './routes/_app/app/tags/index'
import { Route as AppAppSettingsIndexRouteImport } from './routes/_app/app/settings/index'
import { Route as AppAppRecipesIndexRouteImport } from './routes/_app/app/recipes/index'
import { Route as AppAppIngredientsIndexRouteImport } from './routes/_app/app/ingredients/index'
import { Route as AppAppRecipesCreateRouteImport } from './routes/_app/app/recipes/create'
import { Route as AppAppTagsTagIdTagRouteImport } from './routes/_app/app/tags/$tagId/_tag'
import { Route as AppAppRecipesRecipeIdRecipesRouteImport } from './routes/_app/app/recipes/$recipeId/_recipes'
import { Route as AppAppTagsTagIdTagIndexRouteImport } from './routes/_app/app/tags/$tagId/_tag/index'
import { Route as AppAppRecipesRecipeIdRecipesIndexRouteImport } from './routes/_app/app/recipes/$recipeId/_recipes/index'
import { Route as AppAppRecipesRecipeIdRecipesUpdateRouteImport } from './routes/_app/app/recipes/$recipeId/_recipes/update'

const AppLazyRouteImport = createFileRoute('/_app')()

const AppLazyRoute = AppLazyRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/_app.lazy').then((d) => d.Route))
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAppTagsIndexRoute = AppAppTagsIndexRouteImport.update({
  id: '/app/tags/',
  path: '/app/tags/',
  getParentRoute: () => AppLazyRoute,
} as any)
const AppAppSettingsIndexRoute = AppAppSettingsIndexRouteImport.update({
  id: '/app/settings/',
  path: '/app/settings/',
  getParentRoute: () => AppLazyRoute,
} as any)
const AppAppRecipesIndexRoute = AppAppRecipesIndexRouteImport.update({
  id: '/app/recipes/',
  path: '/app/recipes/',
  getParentRoute: () => AppLazyRoute,
} as any)
const AppAppIngredientsIndexRoute = AppAppIngredientsIndexRouteImport.update({
  id: '/app/ingredients/',
  path: '/app/ingredients/',
  getParentRoute: () => AppLazyRoute,
} as any)
const AppAppRecipesCreateRoute = AppAppRecipesCreateRouteImport.update({
  id: '/app/recipes/create',
  path: '/app/recipes/create',
  getParentRoute: () => AppLazyRoute,
} as any)
const AppAppTagsTagIdTagRoute = AppAppTagsTagIdTagRouteImport.update({
  id: '/app/tags/$tagId/_tag',
  path: '/app/tags/$tagId',
  getParentRoute: () => AppLazyRoute,
} as any)
const AppAppRecipesRecipeIdRecipesRoute =
  AppAppRecipesRecipeIdRecipesRouteImport.update({
    id: '/app/recipes/$recipeId/_recipes',
    path: '/app/recipes/$recipeId',
    getParentRoute: () => AppLazyRoute,
  } as any)
const AppAppTagsTagIdTagIndexRoute = AppAppTagsTagIdTagIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAppTagsTagIdTagRoute,
} as any)
const AppAppRecipesRecipeIdRecipesIndexRoute =
  AppAppRecipesRecipeIdRecipesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppAppRecipesRecipeIdRecipesRoute,
  } as any)
const AppAppRecipesRecipeIdRecipesUpdateRoute =
  AppAppRecipesRecipeIdRecipesUpdateRouteImport.update({
    id: '/update',
    path: '/update',
    getParentRoute: () => AppAppRecipesRecipeIdRecipesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app/recipes/create': typeof AppAppRecipesCreateRoute
  '/app/ingredients/': typeof AppAppIngredientsIndexRoute
  '/app/recipes/': typeof AppAppRecipesIndexRoute
  '/app/settings/': typeof AppAppSettingsIndexRoute
  '/app/tags/': typeof AppAppTagsIndexRoute
  '/app/recipes/$recipeId': typeof AppAppRecipesRecipeIdRecipesRouteWithChildren
  '/app/tags/$tagId': typeof AppAppTagsTagIdTagRouteWithChildren
  '/app/recipes/$recipeId/update': typeof AppAppRecipesRecipeIdRecipesUpdateRoute
  '/app/recipes/$recipeId/': typeof AppAppRecipesRecipeIdRecipesIndexRoute
  '/app/tags/$tagId/': typeof AppAppTagsTagIdTagIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app/recipes/create': typeof AppAppRecipesCreateRoute
  '/app/ingredients': typeof AppAppIngredientsIndexRoute
  '/app/recipes': typeof AppAppRecipesIndexRoute
  '/app/settings': typeof AppAppSettingsIndexRoute
  '/app/tags': typeof AppAppTagsIndexRoute
  '/app/recipes/$recipeId/update': typeof AppAppRecipesRecipeIdRecipesUpdateRoute
  '/app/recipes/$recipeId': typeof AppAppRecipesRecipeIdRecipesIndexRoute
  '/app/tags/$tagId': typeof AppAppTagsTagIdTagIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppLazyRouteWithChildren
  '/_app/app/recipes/create': typeof AppAppRecipesCreateRoute
  '/_app/app/ingredients/': typeof AppAppIngredientsIndexRoute
  '/_app/app/recipes/': typeof AppAppRecipesIndexRoute
  '/_app/app/settings/': typeof AppAppSettingsIndexRoute
  '/_app/app/tags/': typeof AppAppTagsIndexRoute
  '/_app/app/recipes/$recipeId/_recipes': typeof AppAppRecipesRecipeIdRecipesRouteWithChildren
  '/_app/app/tags/$tagId/_tag': typeof AppAppTagsTagIdTagRouteWithChildren
  '/_app/app/recipes/$recipeId/_recipes/update': typeof AppAppRecipesRecipeIdRecipesUpdateRoute
  '/_app/app/recipes/$recipeId/_recipes/': typeof AppAppRecipesRecipeIdRecipesIndexRoute
  '/_app/app/tags/$tagId/_tag/': typeof AppAppTagsTagIdTagIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app/recipes/create'
    | '/app/ingredients/'
    | '/app/recipes/'
    | '/app/settings/'
    | '/app/tags/'
    | '/app/recipes/$recipeId'
    | '/app/tags/$tagId'
    | '/app/recipes/$recipeId/update'
    | '/app/recipes/$recipeId/'
    | '/app/tags/$tagId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app/recipes/create'
    | '/app/ingredients'
    | '/app/recipes'
    | '/app/settings'
    | '/app/tags'
    | '/app/recipes/$recipeId/update'
    | '/app/recipes/$recipeId'
    | '/app/tags/$tagId'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/app/recipes/create'
    | '/_app/app/ingredients/'
    | '/_app/app/recipes/'
    | '/_app/app/settings/'
    | '/_app/app/tags/'
    | '/_app/app/recipes/$recipeId/_recipes'
    | '/_app/app/tags/$tagId/_tag'
    | '/_app/app/recipes/$recipeId/_recipes/update'
    | '/_app/app/recipes/$recipeId/_recipes/'
    | '/_app/app/tags/$tagId/_tag/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppLazyRoute: typeof AppLazyRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/app/tags/': {
      id: '/_app/app/tags/'
      path: '/app/tags'
      fullPath: '/app/tags/'
      preLoaderRoute: typeof AppAppTagsIndexRouteImport
      parentRoute: typeof AppLazyRoute
    }
    '/_app/app/settings/': {
      id: '/_app/app/settings/'
      path: '/app/settings'
      fullPath: '/app/settings/'
      preLoaderRoute: typeof AppAppSettingsIndexRouteImport
      parentRoute: typeof AppLazyRoute
    }
    '/_app/app/recipes/': {
      id: '/_app/app/recipes/'
      path: '/app/recipes'
      fullPath: '/app/recipes/'
      preLoaderRoute: typeof AppAppRecipesIndexRouteImport
      parentRoute: typeof AppLazyRoute
    }
    '/_app/app/ingredients/': {
      id: '/_app/app/ingredients/'
      path: '/app/ingredients'
      fullPath: '/app/ingredients/'
      preLoaderRoute: typeof AppAppIngredientsIndexRouteImport
      parentRoute: typeof AppLazyRoute
    }
    '/_app/app/recipes/create': {
      id: '/_app/app/recipes/create'
      path: '/app/recipes/create'
      fullPath: '/app/recipes/create'
      preLoaderRoute: typeof AppAppRecipesCreateRouteImport
      parentRoute: typeof AppLazyRoute
    }
    '/_app/app/tags/$tagId/_tag': {
      id: '/_app/app/tags/$tagId/_tag'
      path: '/app/tags/$tagId'
      fullPath: '/app/tags/$tagId'
      preLoaderRoute: typeof AppAppTagsTagIdTagRouteImport
      parentRoute: typeof AppLazyRoute
    }
    '/_app/app/recipes/$recipeId/_recipes': {
      id: '/_app/app/recipes/$recipeId/_recipes'
      path: '/app/recipes/$recipeId'
      fullPath: '/app/recipes/$recipeId'
      preLoaderRoute: typeof AppAppRecipesRecipeIdRecipesRouteImport
      parentRoute: typeof AppLazyRoute
    }
    '/_app/app/tags/$tagId/_tag/': {
      id: '/_app/app/tags/$tagId/_tag/'
      path: '/'
      fullPath: '/app/tags/$tagId/'
      preLoaderRoute: typeof AppAppTagsTagIdTagIndexRouteImport
      parentRoute: typeof AppAppTagsTagIdTagRoute
    }
    '/_app/app/recipes/$recipeId/_recipes/': {
      id: '/_app/app/recipes/$recipeId/_recipes/'
      path: '/'
      fullPath: '/app/recipes/$recipeId/'
      preLoaderRoute: typeof AppAppRecipesRecipeIdRecipesIndexRouteImport
      parentRoute: typeof AppAppRecipesRecipeIdRecipesRoute
    }
    '/_app/app/recipes/$recipeId/_recipes/update': {
      id: '/_app/app/recipes/$recipeId/_recipes/update'
      path: '/update'
      fullPath: '/app/recipes/$recipeId/update'
      preLoaderRoute: typeof AppAppRecipesRecipeIdRecipesUpdateRouteImport
      parentRoute: typeof AppAppRecipesRecipeIdRecipesRoute
    }
  }
}

interface AppAppRecipesRecipeIdRecipesRouteChildren {
  AppAppRecipesRecipeIdRecipesUpdateRoute: typeof AppAppRecipesRecipeIdRecipesUpdateRoute
  AppAppRecipesRecipeIdRecipesIndexRoute: typeof AppAppRecipesRecipeIdRecipesIndexRoute
}

const AppAppRecipesRecipeIdRecipesRouteChildren: AppAppRecipesRecipeIdRecipesRouteChildren =
  {
    AppAppRecipesRecipeIdRecipesUpdateRoute:
      AppAppRecipesRecipeIdRecipesUpdateRoute,
    AppAppRecipesRecipeIdRecipesIndexRoute:
      AppAppRecipesRecipeIdRecipesIndexRoute,
  }

const AppAppRecipesRecipeIdRecipesRouteWithChildren =
  AppAppRecipesRecipeIdRecipesRoute._addFileChildren(
    AppAppRecipesRecipeIdRecipesRouteChildren,
  )

interface AppAppTagsTagIdTagRouteChildren {
  AppAppTagsTagIdTagIndexRoute: typeof AppAppTagsTagIdTagIndexRoute
}

const AppAppTagsTagIdTagRouteChildren: AppAppTagsTagIdTagRouteChildren = {
  AppAppTagsTagIdTagIndexRoute: AppAppTagsTagIdTagIndexRoute,
}

const AppAppTagsTagIdTagRouteWithChildren =
  AppAppTagsTagIdTagRoute._addFileChildren(AppAppTagsTagIdTagRouteChildren)

interface AppLazyRouteChildren {
  AppAppRecipesCreateRoute: typeof AppAppRecipesCreateRoute
  AppAppIngredientsIndexRoute: typeof AppAppIngredientsIndexRoute
  AppAppRecipesIndexRoute: typeof AppAppRecipesIndexRoute
  AppAppSettingsIndexRoute: typeof AppAppSettingsIndexRoute
  AppAppTagsIndexRoute: typeof AppAppTagsIndexRoute
  AppAppRecipesRecipeIdRecipesRoute: typeof AppAppRecipesRecipeIdRecipesRouteWithChildren
  AppAppTagsTagIdTagRoute: typeof AppAppTagsTagIdTagRouteWithChildren
}

const AppLazyRouteChildren: AppLazyRouteChildren = {
  AppAppRecipesCreateRoute: AppAppRecipesCreateRoute,
  AppAppIngredientsIndexRoute: AppAppIngredientsIndexRoute,
  AppAppRecipesIndexRoute: AppAppRecipesIndexRoute,
  AppAppSettingsIndexRoute: AppAppSettingsIndexRoute,
  AppAppTagsIndexRoute: AppAppTagsIndexRoute,
  AppAppRecipesRecipeIdRecipesRoute:
    AppAppRecipesRecipeIdRecipesRouteWithChildren,
  AppAppTagsTagIdTagRoute: AppAppTagsTagIdTagRouteWithChildren,
}

const AppLazyRouteWithChildren =
  AppLazyRoute._addFileChildren(AppLazyRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppLazyRoute: AppLazyRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
