/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as AppAppTagsIndexImport } from './routes/_app/app/tags/index'
import { Route as AppAppSettingsIndexImport } from './routes/_app/app/settings/index'
import { Route as AppAppRecipesIndexImport } from './routes/_app/app/recipes/index'
import { Route as AppAppIngredientsIndexImport } from './routes/_app/app/ingredients/index'
import { Route as AppAppRecipesCreateImport } from './routes/_app/app/recipes/create'
import { Route as AppAppRecipesRecipeIdIndexImport } from './routes/_app/app/recipes/$recipeId/index'
import { Route as AppAppTagsTagIdTagImport } from './routes/_app/app/tags/$tagId/_tag'
import { Route as AppAppRecipesRecipeIdUpdateImport } from './routes/_app/app/recipes/$recipeId/update'
import { Route as AppAppTagsTagIdTagRecipeImport } from './routes/_app/app/tags/$tagId/_tag/recipe'
import { Route as AppAppTagsTagIdTagInfoImport } from './routes/_app/app/tags/$tagId/_tag/info'

// Create Virtual Routes

const AppLazyImport = createFileRoute('/_app')()
const AppAppTagsTagIdImport = createFileRoute('/_app/app/tags/$tagId')()

// Create/Update Routes

const AppLazyRoute = AppLazyImport.update({
  id: '/_app',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/_app.lazy').then((d) => d.Route))

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AppAppTagsTagIdRoute = AppAppTagsTagIdImport.update({
  id: '/app/tags/$tagId',
  path: '/app/tags/$tagId',
  getParentRoute: () => AppLazyRoute,
} as any)

const AppAppTagsIndexRoute = AppAppTagsIndexImport.update({
  id: '/app/tags/',
  path: '/app/tags/',
  getParentRoute: () => AppLazyRoute,
} as any)

const AppAppSettingsIndexRoute = AppAppSettingsIndexImport.update({
  id: '/app/settings/',
  path: '/app/settings/',
  getParentRoute: () => AppLazyRoute,
} as any)

const AppAppRecipesIndexRoute = AppAppRecipesIndexImport.update({
  id: '/app/recipes/',
  path: '/app/recipes/',
  getParentRoute: () => AppLazyRoute,
} as any)

const AppAppIngredientsIndexRoute = AppAppIngredientsIndexImport.update({
  id: '/app/ingredients/',
  path: '/app/ingredients/',
  getParentRoute: () => AppLazyRoute,
} as any)

const AppAppRecipesCreateRoute = AppAppRecipesCreateImport.update({
  id: '/app/recipes/create',
  path: '/app/recipes/create',
  getParentRoute: () => AppLazyRoute,
} as any)

const AppAppRecipesRecipeIdIndexRoute = AppAppRecipesRecipeIdIndexImport.update(
  {
    id: '/app/recipes/$recipeId/',
    path: '/app/recipes/$recipeId/',
    getParentRoute: () => AppLazyRoute,
  } as any,
)

const AppAppTagsTagIdTagRoute = AppAppTagsTagIdTagImport.update({
  id: '/_tag',
  getParentRoute: () => AppAppTagsTagIdRoute,
} as any)

const AppAppRecipesRecipeIdUpdateRoute =
  AppAppRecipesRecipeIdUpdateImport.update({
    id: '/app/recipes/$recipeId/update',
    path: '/app/recipes/$recipeId/update',
    getParentRoute: () => AppLazyRoute,
  } as any)

const AppAppTagsTagIdTagRecipeRoute = AppAppTagsTagIdTagRecipeImport.update({
  id: '/recipe',
  path: '/recipe',
  getParentRoute: () => AppAppTagsTagIdTagRoute,
} as any)

const AppAppTagsTagIdTagInfoRoute = AppAppTagsTagIdTagInfoImport.update({
  id: '/info',
  path: '/info',
  getParentRoute: () => AppAppTagsTagIdTagRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppLazyImport
      parentRoute: typeof rootRoute
    }
    '/_app/app/recipes/create': {
      id: '/_app/app/recipes/create'
      path: '/app/recipes/create'
      fullPath: '/app/recipes/create'
      preLoaderRoute: typeof AppAppRecipesCreateImport
      parentRoute: typeof AppLazyImport
    }
    '/_app/app/ingredients/': {
      id: '/_app/app/ingredients/'
      path: '/app/ingredients'
      fullPath: '/app/ingredients'
      preLoaderRoute: typeof AppAppIngredientsIndexImport
      parentRoute: typeof AppLazyImport
    }
    '/_app/app/recipes/': {
      id: '/_app/app/recipes/'
      path: '/app/recipes'
      fullPath: '/app/recipes'
      preLoaderRoute: typeof AppAppRecipesIndexImport
      parentRoute: typeof AppLazyImport
    }
    '/_app/app/settings/': {
      id: '/_app/app/settings/'
      path: '/app/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppAppSettingsIndexImport
      parentRoute: typeof AppLazyImport
    }
    '/_app/app/tags/': {
      id: '/_app/app/tags/'
      path: '/app/tags'
      fullPath: '/app/tags'
      preLoaderRoute: typeof AppAppTagsIndexImport
      parentRoute: typeof AppLazyImport
    }
    '/_app/app/recipes/$recipeId/update': {
      id: '/_app/app/recipes/$recipeId/update'
      path: '/app/recipes/$recipeId/update'
      fullPath: '/app/recipes/$recipeId/update'
      preLoaderRoute: typeof AppAppRecipesRecipeIdUpdateImport
      parentRoute: typeof AppLazyImport
    }
    '/_app/app/tags/$tagId': {
      id: '/_app/app/tags/$tagId'
      path: '/app/tags/$tagId'
      fullPath: '/app/tags/$tagId'
      preLoaderRoute: typeof AppAppTagsTagIdImport
      parentRoute: typeof AppLazyImport
    }
    '/_app/app/tags/$tagId/_tag': {
      id: '/_app/app/tags/$tagId/_tag'
      path: '/app/tags/$tagId'
      fullPath: '/app/tags/$tagId'
      preLoaderRoute: typeof AppAppTagsTagIdTagImport
      parentRoute: typeof AppAppTagsTagIdRoute
    }
    '/_app/app/recipes/$recipeId/': {
      id: '/_app/app/recipes/$recipeId/'
      path: '/app/recipes/$recipeId'
      fullPath: '/app/recipes/$recipeId'
      preLoaderRoute: typeof AppAppRecipesRecipeIdIndexImport
      parentRoute: typeof AppLazyImport
    }
    '/_app/app/tags/$tagId/_tag/info': {
      id: '/_app/app/tags/$tagId/_tag/info'
      path: '/info'
      fullPath: '/app/tags/$tagId/info'
      preLoaderRoute: typeof AppAppTagsTagIdTagInfoImport
      parentRoute: typeof AppAppTagsTagIdTagImport
    }
    '/_app/app/tags/$tagId/_tag/recipe': {
      id: '/_app/app/tags/$tagId/_tag/recipe'
      path: '/recipe'
      fullPath: '/app/tags/$tagId/recipe'
      preLoaderRoute: typeof AppAppTagsTagIdTagRecipeImport
      parentRoute: typeof AppAppTagsTagIdTagImport
    }
  }
}

// Create and export the route tree

interface AppAppTagsTagIdTagRouteChildren {
  AppAppTagsTagIdTagInfoRoute: typeof AppAppTagsTagIdTagInfoRoute
  AppAppTagsTagIdTagRecipeRoute: typeof AppAppTagsTagIdTagRecipeRoute
}

const AppAppTagsTagIdTagRouteChildren: AppAppTagsTagIdTagRouteChildren = {
  AppAppTagsTagIdTagInfoRoute: AppAppTagsTagIdTagInfoRoute,
  AppAppTagsTagIdTagRecipeRoute: AppAppTagsTagIdTagRecipeRoute,
}

const AppAppTagsTagIdTagRouteWithChildren =
  AppAppTagsTagIdTagRoute._addFileChildren(AppAppTagsTagIdTagRouteChildren)

interface AppAppTagsTagIdRouteChildren {
  AppAppTagsTagIdTagRoute: typeof AppAppTagsTagIdTagRouteWithChildren
}

const AppAppTagsTagIdRouteChildren: AppAppTagsTagIdRouteChildren = {
  AppAppTagsTagIdTagRoute: AppAppTagsTagIdTagRouteWithChildren,
}

const AppAppTagsTagIdRouteWithChildren = AppAppTagsTagIdRoute._addFileChildren(
  AppAppTagsTagIdRouteChildren,
)

interface AppLazyRouteChildren {
  AppAppRecipesCreateRoute: typeof AppAppRecipesCreateRoute
  AppAppIngredientsIndexRoute: typeof AppAppIngredientsIndexRoute
  AppAppRecipesIndexRoute: typeof AppAppRecipesIndexRoute
  AppAppSettingsIndexRoute: typeof AppAppSettingsIndexRoute
  AppAppTagsIndexRoute: typeof AppAppTagsIndexRoute
  AppAppRecipesRecipeIdUpdateRoute: typeof AppAppRecipesRecipeIdUpdateRoute
  AppAppTagsTagIdRoute: typeof AppAppTagsTagIdRouteWithChildren
  AppAppRecipesRecipeIdIndexRoute: typeof AppAppRecipesRecipeIdIndexRoute
}

const AppLazyRouteChildren: AppLazyRouteChildren = {
  AppAppRecipesCreateRoute: AppAppRecipesCreateRoute,
  AppAppIngredientsIndexRoute: AppAppIngredientsIndexRoute,
  AppAppRecipesIndexRoute: AppAppRecipesIndexRoute,
  AppAppSettingsIndexRoute: AppAppSettingsIndexRoute,
  AppAppTagsIndexRoute: AppAppTagsIndexRoute,
  AppAppRecipesRecipeIdUpdateRoute: AppAppRecipesRecipeIdUpdateRoute,
  AppAppTagsTagIdRoute: AppAppTagsTagIdRouteWithChildren,
  AppAppRecipesRecipeIdIndexRoute: AppAppRecipesRecipeIdIndexRoute,
}

const AppLazyRouteWithChildren =
  AppLazyRoute._addFileChildren(AppLazyRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof AppLazyRouteWithChildren
  '/app/recipes/create': typeof AppAppRecipesCreateRoute
  '/app/ingredients': typeof AppAppIngredientsIndexRoute
  '/app/recipes': typeof AppAppRecipesIndexRoute
  '/app/settings': typeof AppAppSettingsIndexRoute
  '/app/tags': typeof AppAppTagsIndexRoute
  '/app/recipes/$recipeId/update': typeof AppAppRecipesRecipeIdUpdateRoute
  '/app/tags/$tagId': typeof AppAppTagsTagIdTagRouteWithChildren
  '/app/recipes/$recipeId': typeof AppAppRecipesRecipeIdIndexRoute
  '/app/tags/$tagId/info': typeof AppAppTagsTagIdTagInfoRoute
  '/app/tags/$tagId/recipe': typeof AppAppTagsTagIdTagRecipeRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof AppLazyRouteWithChildren
  '/app/recipes/create': typeof AppAppRecipesCreateRoute
  '/app/ingredients': typeof AppAppIngredientsIndexRoute
  '/app/recipes': typeof AppAppRecipesIndexRoute
  '/app/settings': typeof AppAppSettingsIndexRoute
  '/app/tags': typeof AppAppTagsIndexRoute
  '/app/recipes/$recipeId/update': typeof AppAppRecipesRecipeIdUpdateRoute
  '/app/tags/$tagId': typeof AppAppTagsTagIdTagRouteWithChildren
  '/app/recipes/$recipeId': typeof AppAppRecipesRecipeIdIndexRoute
  '/app/tags/$tagId/info': typeof AppAppTagsTagIdTagInfoRoute
  '/app/tags/$tagId/recipe': typeof AppAppTagsTagIdTagRecipeRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_app': typeof AppLazyRouteWithChildren
  '/_app/app/recipes/create': typeof AppAppRecipesCreateRoute
  '/_app/app/ingredients/': typeof AppAppIngredientsIndexRoute
  '/_app/app/recipes/': typeof AppAppRecipesIndexRoute
  '/_app/app/settings/': typeof AppAppSettingsIndexRoute
  '/_app/app/tags/': typeof AppAppTagsIndexRoute
  '/_app/app/recipes/$recipeId/update': typeof AppAppRecipesRecipeIdUpdateRoute
  '/_app/app/tags/$tagId': typeof AppAppTagsTagIdRouteWithChildren
  '/_app/app/tags/$tagId/_tag': typeof AppAppTagsTagIdTagRouteWithChildren
  '/_app/app/recipes/$recipeId/': typeof AppAppRecipesRecipeIdIndexRoute
  '/_app/app/tags/$tagId/_tag/info': typeof AppAppTagsTagIdTagInfoRoute
  '/_app/app/tags/$tagId/_tag/recipe': typeof AppAppTagsTagIdTagRecipeRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/app/recipes/create'
    | '/app/ingredients'
    | '/app/recipes'
    | '/app/settings'
    | '/app/tags'
    | '/app/recipes/$recipeId/update'
    | '/app/tags/$tagId'
    | '/app/recipes/$recipeId'
    | '/app/tags/$tagId/info'
    | '/app/tags/$tagId/recipe'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/app/recipes/create'
    | '/app/ingredients'
    | '/app/recipes'
    | '/app/settings'
    | '/app/tags'
    | '/app/recipes/$recipeId/update'
    | '/app/tags/$tagId'
    | '/app/recipes/$recipeId'
    | '/app/tags/$tagId/info'
    | '/app/tags/$tagId/recipe'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/app/recipes/create'
    | '/_app/app/ingredients/'
    | '/_app/app/recipes/'
    | '/_app/app/settings/'
    | '/_app/app/tags/'
    | '/_app/app/recipes/$recipeId/update'
    | '/_app/app/tags/$tagId'
    | '/_app/app/tags/$tagId/_tag'
    | '/_app/app/recipes/$recipeId/'
    | '/_app/app/tags/$tagId/_tag/info'
    | '/_app/app/tags/$tagId/_tag/recipe'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppLazyRoute: typeof AppLazyRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppLazyRoute: AppLazyRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_app"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_app": {
      "filePath": "_app.lazy.tsx",
      "children": [
        "/_app/app/recipes/create",
        "/_app/app/ingredients/",
        "/_app/app/recipes/",
        "/_app/app/settings/",
        "/_app/app/tags/",
        "/_app/app/recipes/$recipeId/update",
        "/_app/app/tags/$tagId",
        "/_app/app/recipes/$recipeId/"
      ]
    },
    "/_app/app/recipes/create": {
      "filePath": "_app/app/recipes/create.tsx",
      "parent": "/_app"
    },
    "/_app/app/ingredients/": {
      "filePath": "_app/app/ingredients/index.tsx",
      "parent": "/_app"
    },
    "/_app/app/recipes/": {
      "filePath": "_app/app/recipes/index.tsx",
      "parent": "/_app"
    },
    "/_app/app/settings/": {
      "filePath": "_app/app/settings/index.tsx",
      "parent": "/_app"
    },
    "/_app/app/tags/": {
      "filePath": "_app/app/tags/index.tsx",
      "parent": "/_app"
    },
    "/_app/app/recipes/$recipeId/update": {
      "filePath": "_app/app/recipes/$recipeId/update.tsx",
      "parent": "/_app"
    },
    "/_app/app/tags/$tagId": {
      "filePath": "_app/app/tags/$tagId",
      "parent": "/_app",
      "children": [
        "/_app/app/tags/$tagId/_tag"
      ]
    },
    "/_app/app/tags/$tagId/_tag": {
      "filePath": "_app/app/tags/$tagId/_tag.tsx",
      "parent": "/_app/app/tags/$tagId",
      "children": [
        "/_app/app/tags/$tagId/_tag/info",
        "/_app/app/tags/$tagId/_tag/recipe"
      ]
    },
    "/_app/app/recipes/$recipeId/": {
      "filePath": "_app/app/recipes/$recipeId/index.tsx",
      "parent": "/_app"
    },
    "/_app/app/tags/$tagId/_tag/info": {
      "filePath": "_app/app/tags/$tagId/_tag/info.tsx",
      "parent": "/_app/app/tags/$tagId/_tag"
    },
    "/_app/app/tags/$tagId/_tag/recipe": {
      "filePath": "_app/app/tags/$tagId/_tag/recipe.tsx",
      "parent": "/_app/app/tags/$tagId/_tag"
    }
  }
}
ROUTE_MANIFEST_END */
